"""create database

Revision ID: 1fea39bd62e8
Revises: 3437fed1f63f
Create Date: 2023-05-20 10:20:54.936560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fea39bd62e8'
down_revision = '3437fed1f63f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
